#!/usr/bin/env python3
"""Write beams/fir1-k63-ineel-20mev.json from beams/fir1-k63-ineel-spectrum.json.

The 120-bin INEEL-digitized spectrum runs to 40 MeV, but the ENDF/B-VIII.1
neutron library (the OpenMC verification path and the multigroup data) ends at
20 MeV, so a source above 20 MeV cannot be run there. The weight above 20 MeV
is 2.1e-9 of the total. This script clips the histogram at 20 MeV (the bin
that straddles it keeps its uniform-in-bin fraction below 20 MeV) and
renormalizes the bin weights to sum to 1; everything else, including the
fluence-rate normalization, is unchanged. The source file is not modified.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CUT = 2.0e7

with open(os.path.join(HERE, "fir1-k63-ineel-spectrum.json")) as f:
    beam = json.load(f)

energy = beam["source"]["energy"]
edges = energy["energy_boundaries_ev"]
weights = energy["bin_weights"]
new_edges = [edges[0]]
new_weights = []
for i, w in enumerate(weights):
    lo, hi = edges[i], edges[i + 1]
    if lo >= CUT:
        break
    if hi > CUT:
        w = w * (CUT - lo) / (hi - lo)
        hi = CUT
    new_edges.append(hi)
    new_weights.append(w)
total = sum(new_weights)
dropped = 1.0 - total / sum(weights)
new_weights = [w / total for w in new_weights]
energy["energy_boundaries_ev"] = new_edges
energy["bin_weights"] = new_weights

new_id = "nctforge.beam.fir1-k63-ineel-20mev.v1"
beam["id"] = new_id
beam["source"]["id"] = new_id
beam["name"] = "FiR 1 K63 epithermal neutron beam — INEEL-digitized spectrum, clipped at 20 MeV"
beam["provenance"]["derivation_note"] += (
    " This variant is clipped at 20 MeV (the upper edge of the ENDF/B-VIII.1 neutron library) "
    f"and renormalized; the clipped weight is {dropped:.2e} of the total. Generated by "
    "beams/make-ineel-20mev.py from fir1-k63-ineel-spectrum.json."
)
with open(os.path.join(HERE, "fir1-k63-ineel-20mev.json"), "w") as f:
    json.dump(beam, f, indent=1)
    f.write("\n")
print(f"{len(new_weights)} bins to {new_edges[-1]:.4g} eV; clipped weight {dropped:.3e}")
