// SPDX-License-Identifier: MIT

//! Automated S_N-vs-continuous-energy regression suite.
//!
//! Each test solves one case with the deterministic multigroup solver at its
//! DEFAULT options (P1 scattering chosen automatically, Anderson depth 3) plus
//! the flags the case itself requires (`--periodic`, `--source-weighting
//! uniform_in_bin`, a larger `--max-outer` where the default 32 sweeps do not
//! reach the 1e-6 target), and compares the result to the committed OpenMC
//! 0.16.0 / ENDF/B-VIII.1 reference in `validation/regression/<case>/`
//! (generated by that directory's `generate_reference.py`; see its README for
//! the physics and normalization).
//!
//! These are regression guards, not accuracy certificates. Tolerances are set
//! from the agreement measured when the suite was written (recorded next to
//! each check) plus margin, so they catch factor-level errors (a ~7x dose error
//! sat in the default path for days before this suite existed) and 20%-level
//! drifts. Every case also has a negative test that runs a known-bad
//! configuration and asserts that the same checker rejects it.
//!
//! Debug-build cost (2 rayon threads, shared and heavily loaded machine): solves
//! A ~14 s, B ~32 s, C ~85 s; negatives A ~14 s, B ~21 s, C ~36 s. The whole file
//! runs in ~60 s wall with 4 test threads.

use serde_json::Value;
use std::path::{Path, PathBuf};
use std::process::Command;

const MC_BAND_NAMES: [&str; 3] = ["thermal", "epithermal", "fast"];

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn data_path() -> PathBuf {
    root().join("benchmarks/synthetic/layered-head-phantom/multigroup-data-28g-v5-tsl.json")
}

fn case_dir(name: &str) -> PathBuf {
    root().join("validation/regression").join(name)
}

fn read_json(path: &Path) -> Value {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path:?}: {e}"))
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_f64().expect("json number"))
        .collect()
}

/// Run `openbnct sn solve` with the given extra flags; returns the flux JSON
/// (and the dose bundle when `dose` is set). Panics if the solve fails or does
/// not converge.
fn solve(
    dir: &tempfile::TempDir,
    case: &Path,
    assignment: Option<&Path>,
    data: &Path,
    extra: &[&str],
    dose: bool,
) -> (Value, Option<Value>) {
    let flux_path = dir.path().join("flux.json");
    let dose_path = dir.path().join("dose.json");
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_openbnct"));
    cmd.args([
        "sn",
        "solve",
        "--quiet",
        "--source-weighting",
        "uniform_in_bin",
    ])
    .arg("--case")
    .arg(case)
    .arg("--data")
    .arg(data)
    .arg("--output")
    .arg(&flux_path);
    if let Some(a) = assignment {
        cmd.arg("--assignment").arg(a);
    }
    if dose {
        cmd.arg("--dose").arg(&dose_path);
    }
    cmd.args(extra);
    let out = cmd.output().expect("spawn openbnct");
    assert!(
        out.status.success(),
        "openbnct sn solve {extra:?} failed:\n{}\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    let flux = read_json(&flux_path);
    assert_eq!(flux["converged"], Value::Bool(true), "solve must converge");
    let dose = dose.then(|| read_json(&dose_path));
    (flux, dose)
}

/// Band (0 thermal < 0.5 eV, 1 epithermal to 10 keV, 2 fast) of each S_N group,
/// from the artifact's descending boundaries.
fn group_bands(flux: &Value) -> Vec<usize> {
    let b = f64s(&flux["energy_boundaries_ev"]);
    (0..b.len() - 1)
        .map(|g| {
            let hi = b[g];
            if hi <= 0.5 * (1.0 + 1e-9) {
                0
            } else if hi <= 1.0e4 * (1.0 + 1e-9) {
                1
            } else {
                2
            }
        })
        .collect()
}

/// Per-cell band fluxes `[cell][band]` of an S_N flux artifact.
fn cell_bands(flux: &Value) -> Vec<[f64; 3]> {
    let bands = group_bands(flux);
    flux["flux"]
        .as_array()
        .expect("flux array")
        .iter()
        .map(|cell| {
            let mut out = [0.0; 3];
            for (g, v) in f64s(cell).iter().enumerate() {
                out[bands[g]] += v;
            }
            out
        })
        .collect()
}

/// Accumulates check failures so a report lists every violated bound.
#[derive(Default)]
struct Checks {
    failures: Vec<String>,
    log: Vec<String>,
}

impl Checks {
    /// `ratio` must lie in `[lo, hi]`.
    fn ratio(&mut self, label: &str, ratio: f64, lo: f64, hi: f64) {
        self.log
            .push(format!("{label}: {ratio:.4} (window {lo}..{hi})"));
        if !(ratio >= lo && ratio <= hi) {
            self.failures
                .push(format!("{label}: S_N/MC = {ratio:.4} outside [{lo}, {hi}]"));
        }
    }
    fn report(&self) -> String {
        format!(
            "{}\nFAILED:\n{}",
            self.log.join("\n"),
            self.failures.join("\n")
        )
    }
    /// Positive test: print the measured ratios (visible with `--nocapture`).
    fn assert_pass(&self) {
        eprintln!("{}", self.log.join("\n"));
        assert!(self.failures.is_empty(), "{}", self.report());
    }
    /// Negative test: the known-bad configuration must be rejected.
    fn assert_rejects(&self, what: &str) {
        eprintln!("negative test ({what}):\n{}", self.report());
        assert!(
            !self.failures.is_empty(),
            "guards are blind: {what} passed every check\n{}",
            self.report()
        );
    }
}

// ---------------------------------------------------------------------------
// Case A: infinite brain medium (4x4x4 cells of 2 cm, periodic), uniform
// volumetric source q = 1 /cm3 (weight V = 512 cm3).
// ---------------------------------------------------------------------------

/// Measured when written (P1, default options; 18 outer iterations):
/// thermal 0.972, epithermal 1.042, fast 0.890, absorbed/source 0.9999.
/// The fast deficit (S_N low by ~11%) is known and unexplained; it is recorded,
/// not fixed, by the ±20% window. Windows: thermal/epithermal ±10%, fast ±20%.
fn check_infinite_medium(flux: &Value) -> Checks {
    let reference = read_json(&case_dir("infinite-medium-brain").join("reference.json"));
    let mc_bands = f64s(&reference["band_flux_mean"]);
    let cells = cell_bands(flux);
    let n = cells.len() as f64;
    let mut c = Checks::default();
    let windows = [(0.90, 1.10), (0.90, 1.10), (0.80, 1.20)];
    for b in 0..3 {
        // Mean cell flux == MC track length summed over the cube (README).
        let sn: f64 = cells.iter().map(|x| x[b]).sum::<f64>() / n;
        c.ratio(
            &format!("A {} flux", MC_BAND_NAMES[b]),
            sn / mc_bands[b],
            windows[b].0,
            windows[b].1,
        );
    }
    // Infinite medium: every source neutron is absorbed. `balance` is the
    // absolute rate for the declared weight (512).
    let weight = 512.0;
    let absorbed = flux["balance_absorbed_fraction"].as_f64().unwrap() / weight;
    c.ratio("A absorbed per source neutron", absorbed, 0.98, 1.02);
    c
}

fn infinite_medium_args() -> Vec<&'static str> {
    vec!["--periodic", "x,y,z"]
}

#[test]
fn regression_a_infinite_medium_matches_mc() {
    let dir = tempfile::tempdir().unwrap();
    let case = case_dir("infinite-medium-brain").join("sn-case.json");
    let (flux, _) = solve(
        &dir,
        &case,
        None,
        &data_path(),
        &infinite_medium_args(),
        false,
    );
    check_infinite_medium(&flux).assert_pass();
}

/// Known-bad configuration: every group's absorption cross section raised by
/// 20% (sigma_t += 0.2 * (sigma_t - sum of out-scatter)). A defect of this size
/// must trip the thermal window (thermal flux falls ~17%).
#[test]
fn regression_a_rejects_perturbed_absorption() {
    let dir = tempfile::tempdir().unwrap();
    let mut data = read_json(&data_path());
    for mat in data["materials"].as_array_mut().unwrap() {
        let sc = f64s(&mat["scatter_matrix_per_cm"]);
        let st = f64s(&mat["sigma_total_per_cm"]);
        let g = st.len();
        let bumped: Vec<Value> = (0..g)
            .map(|i| {
                let out: f64 = sc[i * g..(i + 1) * g].iter().sum();
                Value::from(st[i] + 0.2 * (st[i] - out))
            })
            .collect();
        mat["sigma_total_per_cm"] = Value::Array(bumped);
    }
    let bad = dir.path().join("data-bad.json");
    std::fs::write(&bad, serde_json::to_string(&data).unwrap()).unwrap();
    let case = case_dir("infinite-medium-brain").join("sn-case.json");
    let (flux, _) = solve(&dir, &case, None, &bad, &infinite_medium_args(), false);
    check_infinite_medium(&flux).assert_rejects("sigma_a +20%");
}

// ---------------------------------------------------------------------------
// Case B: 1x1x25 brain column of 8 mm cells, transverse periodic, monodirectional
// +z beam on the z = 0 face (uniform_disk r = 0.6 cm covering the one cell).
// ---------------------------------------------------------------------------

/// Measured when written (P1, default options, `--max-outer 128`, 48 outers):
///   column-total band ratios: thermal 0.912, epithermal 1.052, fast 0.964
///   (window ±25%);
///   absorbed per neutron entering the cell 0.411 vs MC 0.4338 = 0.947
///   (window ±10%);
///   depth zones (voxels 0-7 / 8-16 / 17-24): thermal 0.829 / 1.125 / 1.636,
///   epithermal 1.047 / 1.278 / 0.908, fast 1.025 / 0.951 / 0.846. The deep
///   thermal excess is a known S_N deficiency; zones are guarded as regression
///   windows around the measured ratio (about ±20%), not as accuracy claims.
fn check_column(flux: &Value) -> Checks {
    let reference = read_json(&case_dir("column-1d-brain").join("reference.json"));
    let disk_area = reference["disk_area_cm2"].as_f64().unwrap();
    let mc = f64s(&reference["band_flux_mean_voxel_x_band"]);
    let cells = cell_bands(flux);
    assert_eq!(cells.len(), 25);
    let mut c = Checks::default();
    // Column totals: S_N flux (per source neutron over the disk) times the disk
    // area is the flux per unit areal source density that the reference stores.
    for b in 0..3 {
        let sn: f64 = cells.iter().map(|x| x[b]).sum::<f64>() * disk_area;
        let mcs: f64 = (0..25).map(|k| mc[3 * k + b]).sum();
        c.ratio(
            &format!("B {} column total", MC_BAND_NAMES[b]),
            sn / mcs,
            0.75,
            1.25,
        );
    }
    // Zone windows [lo, hi] per band: front, middle, back.
    let zones = [(0usize, 8usize), (8, 17), (17, 25)];
    let windows = [
        [(0.68, 1.00), (0.95, 1.35), (1.30, 2.00)], // thermal
        [(0.85, 1.25), (1.05, 1.50), (0.72, 1.10)], // epithermal
        [(0.85, 1.20), (0.78, 1.15), (0.68, 1.02)], // fast
    ];
    for b in 0..3 {
        for (zi, (lo, hi)) in zones.iter().enumerate() {
            let sn: f64 = (*lo..*hi).map(|k| cells[k][b]).sum::<f64>() * disk_area;
            let mcs: f64 = (*lo..*hi).map(|k| mc[3 * k + b]).sum();
            let (wl, wh) = windows[b][zi];
            c.ratio(
                &format!("B {} zone {zi}", MC_BAND_NAMES[b]),
                sn / mcs,
                wl,
                wh,
            );
        }
    }
    // Absorption per source neutron ENTERING the modelled cell: the solver's
    // balance is per neutron over the disk, of which cell_area / disk_area
    // reaches the (fully illuminated) 0.8 x 0.8 cm cell.
    let cell_area = 0.8 * 0.8;
    let sn_abs = flux["balance_absorbed_fraction"].as_f64().unwrap() * disk_area / cell_area;
    let mc_abs = reference["absorption_mean"].as_f64().unwrap();
    c.ratio(
        "B absorption per source neutron",
        sn_abs / mc_abs,
        0.90,
        1.10,
    );
    c
}

fn column_args() -> Vec<&'static str> {
    vec!["--periodic", "x,y", "--max-outer", "128"]
}

#[test]
fn regression_b_column_matches_mc() {
    let dir = tempfile::tempdir().unwrap();
    let case = case_dir("column-1d-brain").join("sn-case.json");
    let (flux, _) = solve(&dir, &case, None, &data_path(), &column_args(), false);
    check_column(&flux).assert_pass();
}

/// Known-bad configuration: forced P0 scattering (the pre-P1 default), which
/// absorbs 0.31 per neutron against the MC 0.434 (ratio 0.71, thermal column
/// total 0.68).
#[test]
fn regression_b_rejects_p0() {
    let dir = tempfile::tempdir().unwrap();
    let case = case_dir("column-1d-brain").join("sn-case.json");
    let mut args = column_args();
    args.push("--p0");
    let (flux, _) = solve(&dir, &case, None, &data_path(), &args, false);
    check_column(&flux).assert_rejects("--p0");
}

// ---------------------------------------------------------------------------
// Case C: mini layered head, 9x9x9 cells of 24 mm (3x3x3 majority vote of the
// 25^3 x 8 mm phantom), disk r = 7 cm, cone half-angle 0.1491 rad.
// ---------------------------------------------------------------------------

const B10_MEV: f64 = 2.34;
const N14_MEV: f64 = 0.626;
const MEV_J: f64 = 1.602_176_634e-13;

/// Absorption events per voxel per source neutron implied by a component dose
/// [Gy per source particle]: D * rho / E * V.
fn absorption_from_dose(
    dose: &Value,
    component: &str,
    rho: &[f64],
    mat: &[usize],
    e_mev: f64,
    vol: f64,
) -> Vec<f64> {
    let comp = dose["components"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["component"] == component)
        .unwrap_or_else(|| panic!("dose component {component}"));
    f64s(&comp["values"])
        .iter()
        .zip(mat)
        .map(|(d, &m)| d * rho[m] * 1e-3 / (e_mev * MEV_J) * vol)
        .collect()
}

/// Measured when written (P1, default options, `--max-outer 64`, 36 outers;
/// MC 2e6 histories). The 24 mm grid is optically thick (sigma_t*dx ~ 8 for
/// thermal neutrons in tissue), so S_N is biased LOW against MC by a
/// deterministic, grid-induced amount; the windows are therefore centred on the
/// measured ratios (about ±15%) and guard against change, they are not an
/// accuracy claim:
///   B10 (brain) 0.667; N14 brain 0.639, skin 0.757, skull 0.681;
///   band flux (all voxels) thermal 0.774, epithermal 1.082, fast 0.943.
fn check_mini_head(flux: &Value, dose: &Value) -> Checks {
    let reference = read_json(&case_dir("mini-layered-head").join("reference.json"));
    let assignment = read_json(&case_dir("mini-layered-head").join("sn-assignment.json"));
    // Material index -> density: 1 skin, 2 skull, 3 brain (from the assignment).
    let mut rho = vec![0.0; 4];
    for region in assignment["regions"].as_array().unwrap() {
        let name = region["name"].as_str().unwrap();
        let idx = ["skin", "skull", "brain"]
            .iter()
            .position(|n| name.starts_with(n))
            .unwrap()
            + 1;
        rho[idx] = region["material"]["density_g_cm3"].as_f64().unwrap();
    }
    let mat: Vec<usize> = f64s(&reference["material_of_voxel"])
        .iter()
        .map(|&m| m as usize)
        .collect();
    let vol = reference["voxel_volume_cm3"].as_f64().unwrap();
    let b_sn = absorption_from_dose(dose, "boron", &rho, &mat, B10_MEV, vol);
    let n_sn = absorption_from_dose(dose, "nitrogen", &rho, &mat, N14_MEV, vol);
    let b_mc = f64s(&reference["b10_absorption_mean"]);
    let n_mc = f64s(&reference["n14_absorption_mean"]);

    let region_ratio = |sn: &[f64], mc: &[f64], m: usize| -> f64 {
        let s: f64 = (0..mat.len()).filter(|&i| mat[i] == m).map(|i| sn[i]).sum();
        let r: f64 = (0..mat.len()).filter(|&i| mat[i] == m).map(|i| mc[i]).sum();
        s / r
    };
    let mut c = Checks::default();
    // Boron is present only in the brain (skin/skull carry none).
    c.ratio("C B10 brain", region_ratio(&b_sn, &b_mc, 3), 0.57, 0.77);
    c.ratio("C N14 brain", region_ratio(&n_sn, &n_mc, 3), 0.54, 0.74);
    c.ratio("C N14 skin", region_ratio(&n_sn, &n_mc, 1), 0.64, 0.87);
    c.ratio("C N14 skull", region_ratio(&n_sn, &n_mc, 2), 0.57, 0.79);

    let mc_flux = f64s(&reference["flux_mean_voxel_x_band"]);
    let cells = cell_bands(flux);
    assert_eq!(cells.len(), mat.len());
    let windows = [(0.62, 0.93), (0.90, 1.30), (0.80, 1.10)];
    for b in 0..3 {
        let sn: f64 = cells.iter().map(|x| x[b]).sum();
        let mcs: f64 = (0..mat.len()).map(|i| mc_flux[3 * i + b]).sum();
        c.ratio(
            &format!("C {} flux", MC_BAND_NAMES[b]),
            sn / mcs,
            windows[b].0,
            windows[b].1,
        );
    }
    c
}

fn mini_head_solve(dir: &tempfile::TempDir, extra: &[&str]) -> (Value, Value) {
    let d = case_dir("mini-layered-head");
    let (flux, dose) = solve(
        dir,
        &d.join("sn-case.json"),
        Some(&d.join("sn-assignment.json")),
        &data_path(),
        extra,
        true,
    );
    (flux, dose.unwrap())
}

#[test]
fn regression_c_mini_head_matches_mc() {
    let dir = tempfile::tempdir().unwrap();
    let (flux, dose) = mini_head_solve(&dir, &["--max-outer", "64"]);
    check_mini_head(&flux, &dose).assert_pass();
}

/// Known-bad configuration: the analytic uncollided-beam split disabled, so the
/// 0.1491 rad cone enters as boundary flux on the nearest S4 ordinate. It
/// delivers ~5% of the correct dose (ratios 0.05 against MC).
#[test]
fn regression_c_rejects_no_uncollided_split() {
    let dir = tempfile::tempdir().unwrap();
    let (flux, dose) = mini_head_solve(&dir, &["--max-outer", "64", "--no-uncollided-split"]);
    check_mini_head(&flux, &dose).assert_rejects("--no-uncollided-split");
}
